//
//  AppStrings.swift
//  Scandalicious
//
//  Central localization dictionary for all user-facing strings.
//  Keys map to [languageCode: translatedString].
//

import Foundation

enum AppStrings {
    // [key: [languageCode: translation]]
    static let strings: [String: [String: String]] = [

        // MARK: - Common
        "ok": ["en": "OK", "nl": "OK", "fr": "OK"],
        "cancel": ["en": "Cancel", "nl": "Annuleren", "fr": "Annuler"],
        "done": ["en": "Done", "nl": "Klaar", "fr": "Terminé"],
        "error": ["en": "Error", "nl": "Fout", "fr": "Erreur"],
        "save": ["en": "Save", "nl": "Opslaan", "fr": "Enregistrer"],
        "delete": ["en": "Delete", "nl": "Verwijderen", "fr": "Supprimer"],
        "retry": ["en": "Retry", "nl": "Opnieuw proberen", "fr": "Réessayer"],
        "edit": ["en": "Edit", "nl": "Bewerken", "fr": "Modifier"],
        "loading": ["en": "Loading...", "nl": "Laden...", "fr": "Chargement..."],
        "unknown_error": ["en": "An unknown error occurred", "nl": "Er is een onbekende fout opgetreden", "fr": "Une erreur inconnue s'est produite"],
        "success": ["en": "Success", "nl": "Geslaagd", "fr": "Succès"],
        "or": ["en": "OR", "nl": "OF", "fr": "OU"],

        // MARK: - Login / Auth
        "welcome_to_milo": ["en": "Welcome to Milo", "nl": "Welkom bij Milo", "fr": "Bienvenue sur Milo"],
        "create_account": ["en": "Create your account", "nl": "Maak je account aan", "fr": "Créez votre compte"],
        "sign_in_continue": ["en": "Sign in to continue", "nl": "Meld je aan om verder te gaan", "fr": "Connectez-vous pour continuer"],
        "email": ["en": "Email", "nl": "E-mail", "fr": "E-mail"],
        "password": ["en": "Password", "nl": "Wachtwoord", "fr": "Mot de passe"],
        "sign_up": ["en": "Sign Up", "nl": "Registreren", "fr": "S'inscrire"],
        "sign_in": ["en": "Sign In", "nl": "Aanmelden", "fr": "Se connecter"],
        "sign_out": ["en": "Sign Out", "nl": "Afmelden", "fr": "Se déconnecter"],
        "forgot_password": ["en": "Forgot Password?", "nl": "Wachtwoord vergeten?", "fr": "Mot de passe oublié ?"],
        "continue_google": ["en": "Continue with Google", "nl": "Ga verder met Google", "fr": "Continuer avec Google"],
        "reset_password": ["en": "Reset Password", "nl": "Wachtwoord herstellen", "fr": "Réinitialiser le mot de passe"],
        "send_reset_link": ["en": "Send Reset Link", "nl": "Verstuur herstelkoppeling", "fr": "Envoyer le lien de réinitialisation"],
        "enter_email_reset": ["en": "Enter your email address to receive a password reset link.", "nl": "Voer je e-mailadres in om een herstellink te ontvangen.", "fr": "Entrez votre adresse e-mail pour recevoir un lien de réinitialisation."],
        "dont_have_account_signup": ["en": "Don't have an account? **Sign Up**", "nl": "Nog geen account? **Registreren**", "fr": "Pas encore de compte ? **S'inscrire**"],
        "already_have_account_signin": ["en": "Already have an account? **Sign In**", "nl": "Al een account? **Aanmelden**", "fr": "Déjà un compte ? **Se connecter**"],
        "password_reset_sent": ["en": "Password reset email sent!", "nl": "E-mail voor wachtwoordherstel verstuurd!", "fr": "E-mail de réinitialisation envoyé !"],
        "sign_out_confirm": ["en": "Are you sure you want to sign out?", "nl": "Ben je zeker dat je wilt afmelden?", "fr": "Êtes-vous sûr de vouloir vous déconnecter ?"],

        // MARK: - Onboarding
        "welcome": ["en": "Welcome", "nl": "Welkom", "fr": "Bienvenue"],
        "personalize_experience": ["en": "Let's personalize your experience", "nl": "Laten we je ervaring personaliseren", "fr": "Personnalisons votre expérience"],
        "nickname": ["en": "Nickname", "nl": "Bijnaam", "fr": "Surnom"],
        "age": ["en": "Age", "nl": "Leeftijd", "fr": "Âge"],
        "get_started": ["en": "Get Started", "nl": "Aan de slag", "fr": "Commencer"],

        // MARK: - Gender
        "gender_male": ["en": "Male", "nl": "Man", "fr": "Homme"],
        "gender_female": ["en": "Female", "nl": "Vrouw", "fr": "Femme"],
        "gender_x": ["en": "X", "nl": "X", "fr": "X"],

        // MARK: - Paywall
        "meet_milo": ["en": "Meet Milo", "nl": "Maak kennis met Milo", "fr": "Découvrez Milo"],
        "your_ai_assistant": ["en": "Your AI shopping assistant", "nl": "Je AI-winkelassistent", "fr": "Votre assistant shopping IA"],
        "feature_scan": ["en": "Scan", "nl": "Scan", "fr": "Scanner"],
        "feature_analyze": ["en": "Analyze", "nl": "Analyseer", "fr": "Analyser"],
        "feature_health": ["en": "Health", "nl": "Gezondheid", "fr": "Santé"],
        "feature_chat": ["en": "Chat", "nl": "Chat", "fr": "Chat"],
        "yearly": ["en": "Yearly", "nl": "Jaarlijks", "fr": "Annuel"],
        "monthly": ["en": "Monthly", "nl": "Maandelijks", "fr": "Mensuel"],
        "year": ["en": "year", "nl": "jaar", "fr": "an"],
        "month": ["en": "month", "nl": "maand", "fr": "mois"],
        "best_value": ["en": "BEST VALUE", "nl": "BESTE KEUZE", "fr": "MEILLEUR CHOIX"],
        "start_free_trial": ["en": "Start 14-Day Free Trial", "nl": "Start 14 dagen gratis proefperiode", "fr": "Essai gratuit de 14 jours"],
        "restore_purchases": ["en": "Restore Purchases", "nl": "Aankopen herstellen", "fr": "Restaurer les achats"],
        "terms": ["en": "Terms", "nl": "Voorwaarden", "fr": "Conditions"],
        "privacy": ["en": "Privacy", "nl": "Privacy", "fr": "Confidentialité"],
        "cancel_anytime": ["en": "Cancel anytime. Auto-renews until canceled.", "nl": "Annuleer wanneer je wilt. Verlengt automatisch tot annulering.", "fr": "Annulez à tout moment. Renouvellement automatique jusqu'à annulation."],
        "welcome_success": ["en": "Welcome!", "nl": "Welkom!", "fr": "Bienvenue !"],

        // MARK: - ContentView / Tabs
        "tab_budget": ["en": "Budget", "nl": "Budget", "fr": "Budget"],
        "tab_home": ["en": "Home", "nl": "Home", "fr": "Accueil"],
        "tab_milo": ["en": "Milo", "nl": "Milo", "fr": "Milo"],
        "syncing": ["en": "Syncing", "nl": "Synchroniseren", "fr": "Synchronisation"],
        "synced": ["en": "Synced", "nl": "Gesynchroniseerd", "fr": "Synchronisé"],

        // MARK: - Profile
        "profile": ["en": "Profile", "nl": "Profiel", "fr": "Profil"],
        "personal_information": ["en": "Personal Information", "nl": "Persoonlijke gegevens", "fr": "Informations personnelles"],
        "language": ["en": "Language", "nl": "Taal", "fr": "Langue"],
        "not_set": ["en": "Not set", "nl": "Niet ingesteld", "fr": "Non défini"],
        "saving": ["en": "Saving...", "nl": "Opslaan...", "fr": "Enregistrement..."],
        "save_changes": ["en": "Save Changes", "nl": "Wijzigingen opslaan", "fr": "Enregistrer les modifications"],
        "account": ["en": "Account", "nl": "Account", "fr": "Compte"],
        "not_available": ["en": "Not available", "nl": "Niet beschikbaar", "fr": "Non disponible"],
        "current_plan": ["en": "Current Plan", "nl": "Huidig abonnement", "fr": "Abonnement actuel"],
        "renews_on": ["en": "Renews On", "nl": "Verlengt op", "fr": "Renouvellement le"],
        "trial_ends": ["en": "Trial Ends", "nl": "Proefperiode eindigt", "fr": "Fin de l'essai"],
        "manage_subscription": ["en": "Manage Subscription", "nl": "Abonnement beheren", "fr": "Gérer l'abonnement"],
        "subscription": ["en": "Subscription", "nl": "Abonnement", "fr": "Abonnement"],
        "insights": ["en": "Insights", "nl": "Inzichten", "fr": "Analyses"],
        "year_in_review": ["en": "Year in Review", "nl": "Jaaroverzicht", "fr": "Bilan annuel"],
        "profile_updated": ["en": "Your profile has been updated successfully", "nl": "Je profiel is succesvol bijgewerkt", "fr": "Votre profil a été mis à jour avec succès"],
        "expired": ["en": "Expired", "nl": "Verlopen", "fr": "Expiré"],
        "free": ["en": "Free", "nl": "Gratis", "fr": "Gratuit"],
        "premium_yearly": ["en": "Premium Yearly", "nl": "Premium Jaarlijks", "fr": "Premium Annuel"],
        "premium_monthly": ["en": "Premium Monthly", "nl": "Premium Maandelijks", "fr": "Premium Mensuel"],
        "premium_yearly_trial": ["en": "Premium Yearly (Trial)", "nl": "Premium Jaarlijks (Proef)", "fr": "Premium Annuel (Essai)"],
        "premium_monthly_trial": ["en": "Premium Monthly (Trial)", "nl": "Premium Maandelijks (Proef)", "fr": "Premium Mensuel (Essai)"],

        // MARK: - Overview
        "stores": ["en": "Stores", "nl": "Winkels", "fr": "Magasins"],
        "categories": ["en": "Categories", "nl": "Categorieën", "fr": "Catégories"],
        "failed_load_data": ["en": "Failed to load data", "nl": "Laden van gegevens mislukt", "fr": "Échec du chargement des données"],
        "failed_load_items": ["en": "Failed to load items", "nl": "Laden van items mislukt", "fr": "Échec du chargement des articles"],
        "no_items_found": ["en": "No items found", "nl": "Geen items gevonden", "fr": "Aucun article trouvé"],
        "receipts": ["en": "Receipts", "nl": "Kassatickets", "fr": "Tickets de caisse"],
        "scan_first_receipt": ["en": "Scan your first receipt to get started", "nl": "Scan je eerste kassaticket om te beginnen", "fr": "Scannez votre premier ticket de caisse pour commencer"],
        "no_receipts_period": ["en": "No receipts for this period", "nl": "Geen kassatickets voor deze periode", "fr": "Aucun ticket de caisse pour cette période"],
        "deleting": ["en": "Deleting...", "nl": "Verwijderen...", "fr": "Suppression..."],
        "delete_failed": ["en": "Delete Failed", "nl": "Verwijderen mislukt", "fr": "Échec de la suppression"],
        "spent_this_month": ["en": "SPENT THIS MONTH", "nl": "UITGEGEVEN DEZE MAAND", "fr": "DÉPENSÉ CE MOIS"],
        "no_category_data": ["en": "No category data", "nl": "Geen categoriegegevens", "fr": "Aucune donnée de catégorie"],
        "tap_to_flip_back": ["en": "Tap to flip back", "nl": "Tik om terug te draaien", "fr": "Appuyez pour retourner"],
        "tap_to_flip": ["en": "Tap to flip", "nl": "Tik om te draaien", "fr": "Appuyez pour retourner"],
        "sort_by": ["en": "Sort By", "nl": "Sorteer op", "fr": "Trier par"],
        "filters": ["en": "Filters", "nl": "Filters", "fr": "Filtres"],
        "nutri_score": ["en": "NUTRI SCORE", "nl": "NUTRI SCORE", "fr": "NUTRI SCORE"],
        "all_stores": ["en": "All Stores", "nl": "Alle winkels", "fr": "Tous les magasins"],
        "highest_spend": ["en": "Highest Spend", "nl": "Hoogste uitgave", "fr": "Dépense la plus élevée"],
        "lowest_spend": ["en": "Lowest Spend", "nl": "Laagste uitgave", "fr": "Dépense la plus basse"],
        "store_name_sort": ["en": "Store Name", "nl": "Winkelnaam", "fr": "Nom du magasin"],
        "tap_for_stores": ["en": "Tap for stores", "nl": "Tik voor winkels", "fr": "Appuyez pour les magasins"],
        "tap_for_categories": ["en": "Tap for categories", "nl": "Tik voor categorieën", "fr": "Appuyez pour les catégories"],
        "no_stores_yet": ["en": "No stores yet", "nl": "Nog geen winkels", "fr": "Pas encore de magasins"],
        "no_categories_yet": ["en": "No categories yet", "nl": "Nog geen categorieën", "fr": "Pas encore de catégories"],
        "visits": ["en": "visits", "nl": "bezoeken", "fr": "visites"],
        "spent": ["en": "spent", "nl": "uitgegeven", "fr": "dépensé"],
        "shopping_insights": ["en": "Shopping Insights", "nl": "Winkelinzichten", "fr": "Analyses des courses"],

        // MARK: - Milo AI Chat
        "milo": ["en": "Milo", "nl": "Milo", "fr": "Milo"],
        "milo_subtitle": ["en": "Your helpfull shopping doggo", "nl": "Je behulpzame winkelhondje", "fr": "Votre fidèle chien de courses"],
        "ask_milo": ["en": "Ask Milo anything...", "nl": "Vraag Milo alles...", "fr": "Demandez à Milo..."],
        "prompt_cook_title": ["en": "Cook with what I bought", "nl": "Kook met wat ik kocht", "fr": "Cuisiner avec mes achats"],
        "prompt_cook_subtitle": ["en": "Recipes from my last haul", "nl": "Recepten van mijn laatste aankopen", "fr": "Recettes de mes derniers achats"],
        "prompt_cook_message": ["en": "What meals can I cook using the items from my most recent grocery receipt?", "nl": "Welke gerechten kan ik maken met de items van mijn recentste kassaticket?", "fr": "Quels repas puis-je préparer avec les articles de mon dernier ticket de caisse ?"],
        "prompt_predict_title": ["en": "Predict my next list", "nl": "Voorspel mijn volgende lijstje", "fr": "Prédire ma prochaine liste"],
        "prompt_predict_subtitle": ["en": "What I'll need to restock soon", "nl": "Wat ik binnenkort moet bijkopen", "fr": "Ce que je devrai racheter bientôt"],
        "prompt_predict_message": ["en": "Based on my purchase history, what grocery items will I likely need to restock soon?", "nl": "Op basis van mijn aankoopgeschiedenis, welke boodschappen moet ik binnenkort bijkopen?", "fr": "D'après mon historique d'achats, quels articles devrais-je bientôt racheter ?"],
        "prompt_price_title": ["en": "Spot the price creep", "nl": "Ontdek prijsstijgingen", "fr": "Détecter les hausses de prix"],
        "prompt_price_subtitle": ["en": "Are my groceries getting pricier?", "nl": "Worden mijn boodschappen duurder?", "fr": "Mes courses deviennent-elles plus chères ?"],
        "prompt_price_message": ["en": "Are any of my regularly purchased grocery items getting more expensive over time?", "nl": "Worden sommige van mijn vaste boodschappen geleidelijk duurder?", "fr": "Certains de mes articles habituels deviennent-ils plus chers avec le temps ?"],
        "prompt_health_title": ["en": "Rate my basket", "nl": "Beoordeel mijn winkelmandje", "fr": "Évaluer mon panier"],
        "prompt_health_subtitle": ["en": "Nutrition score breakdown", "nl": "Analyse van je voedingsscore", "fr": "Analyse du score nutritionnel"],
        "prompt_health_message": ["en": "Analyze the nutritional balance of my recent grocery purchases and give me a health score", "nl": "Analyseer het voedingsevenwicht van mijn recente boodschappen en geef me een gezondheidsscore", "fr": "Analysez l'équilibre nutritionnel de mes achats récents et donnez-moi un score santé"],
        "message_limit_reached": ["en": "Message Limit Reached", "nl": "Berichtlimiet bereikt", "fr": "Limite de messages atteinte"],
        "error_encountered": ["en": "I'm sorry, I encountered an error", "nl": "Sorry, er is een fout opgetreden", "fr": "Désolé, une erreur s'est produite"],
        "please_try_again": ["en": "Please try again.", "nl": "Probeer het opnieuw.", "fr": "Veuillez réessayer."],

        // MARK: - Budget
        "set_budget": ["en": "Set Budget", "nl": "Budget instellen", "fr": "Définir le budget"],
        "edit_budget": ["en": "Edit Budget", "nl": "Budget bewerken", "fr": "Modifier le budget"],
        "update_budget": ["en": "Update Budget", "nl": "Budget bijwerken", "fr": "Mettre à jour le budget"],
        "create_budget": ["en": "Create Budget", "nl": "Budget aanmaken", "fr": "Créer un budget"],
        "budget_question": ["en": "How do you want to track your groceries?", "nl": "Hoe wil je je boodschappen bijhouden?", "fr": "Comment souhaitez-vous suivre vos courses ?"],
        "total_monthly_budget": ["en": "Total monthly budget", "nl": "Totaal maandbudget", "fr": "Budget mensuel total"],
        "set_one_amount": ["en": "Set one amount for all groceries", "nl": "Stel één bedrag in voor alle boodschappen", "fr": "Définir un montant pour toutes les courses"],
        "budget_by_category": ["en": "Budget by category", "nl": "Budget per categorie", "fr": "Budget par catégorie"],
        "set_limits_category": ["en": "Set limits per category", "nl": "Stel limieten in per categorie", "fr": "Définir des limites par catégorie"],
        "monthly_budget": ["en": "MONTHLY BUDGET", "nl": "MAANDBUDGET", "fr": "BUDGET MENSUEL"],
        "per_month": ["en": "per month", "nl": "per maand", "fr": "par mois"],
        "category_targets": ["en": "CATEGORY TARGETS", "nl": "CATEGORIEDOELEN", "fr": "OBJECTIFS PAR CATÉGORIE"],
        "category_budgets": ["en": "CATEGORY BUDGETS", "nl": "CATEGORIEBUDGETTEN", "fr": "BUDGETS PAR CATÉGORIE"],
        "optional": ["en": "Optional", "nl": "Optioneel", "fr": "Facultatif"],
        "set_limits_categories_eye": ["en": "Set limits on categories you want to keep an eye on", "nl": "Stel limieten in op categorieën die je in de gaten wilt houden", "fr": "Définissez des limites sur les catégories que vous souhaitez surveiller"],
        "add_category": ["en": "Add category", "nl": "Categorie toevoegen", "fr": "Ajouter une catégorie"],
        "add_category_nav": ["en": "Add Category", "nl": "Categorie toevoegen", "fr": "Ajouter une catégorie"],
        "search_categories": ["en": "Search categories", "nl": "Zoek categorieën", "fr": "Rechercher des catégories"],
        "no_categories_found": ["en": "No categories found", "nl": "Geen categorieën gevonden", "fr": "Aucune catégorie trouvée"],
        "auto_renew": ["en": "Auto-renew", "nl": "Automatisch verlengen", "fr": "Renouvellement automatique"],
        "auto_renew_monthly": ["en": "Auto-renew monthly", "nl": "Maandelijks automatisch verlengen", "fr": "Renouvellement mensuel automatique"],
        "resets_budget_month": ["en": "Resets budget each month", "nl": "Herstelt budget elke maand", "fr": "Réinitialise le budget chaque mois"],
        "reuse_budget_monthly": ["en": "Reuse this budget every month", "nl": "Hergebruik dit budget elke maand", "fr": "Réutiliser ce budget chaque mois"],
        "add_categories_track": ["en": "Add categories you want to track", "nl": "Voeg categorieën toe die je wilt bijhouden", "fr": "Ajoutez les catégories que vous souhaitez suivre"],
        "total_saved": ["en": "TOTAL SAVED", "nl": "TOTAAL BESPAARD", "fr": "TOTAL ÉCONOMISÉ"],
        "budget": ["en": "Budget", "nl": "Budget", "fr": "Budget"],
        "no_budget_month": ["en": "No budget was set for this month", "nl": "Er is geen budget ingesteld voor deze maand", "fr": "Aucun budget n'a été défini pour ce mois"],
        "track_spending": ["en": "Track your spending and stay on track", "nl": "Volg je uitgaven en blijf op koers", "fr": "Suivez vos dépenses et restez sur la bonne voie"],
        "couldnt_load_budget": ["en": "Couldn't load budget", "nl": "Budget laden mislukt", "fr": "Impossible de charger le budget"],
        "remove_budget_confirm": ["en": "This will remove your budget tracking. You can set a new budget anytime.", "nl": "Dit verwijdert je budgetopvolging. Je kunt altijd een nieuw budget instellen.", "fr": "Cela supprimera le suivi de votre budget. Vous pouvez définir un nouveau budget à tout moment."],
        "remove_category_confirm": ["en": "This category will no longer be tracked against a target.", "nl": "Deze categorie wordt niet meer bijgehouden tegenover een doel.", "fr": "Cette catégorie ne sera plus suivie par rapport à un objectif."],
        "remove_target": ["en": "Remove Target", "nl": "Doel verwijderen", "fr": "Supprimer l'objectif"],
        "left_to_spend": ["en": "left to spend", "nl": "nog te besteden", "fr": "reste à dépenser"],
        "days_left": ["en": "days left", "nl": "dagen over", "fr": "jours restants"],
        "no_results": ["en": "No results", "nl": "Geen resultaten", "fr": "Aucun résultat"],
        "no_budget_data": ["en": "No budget data", "nl": "Geen budgetgegevens", "fr": "Aucune donnée de budget"],

        // MARK: - Budget Created
        "budget_created": ["en": "Budget Created!", "nl": "Budget aangemaakt!", "fr": "Budget créé !"],
        "monthly_savings_target": ["en": "Monthly Savings Target", "nl": "Maandelijks besparingsdoel", "fr": "Objectif d'épargne mensuel"],
        "start_tracking": ["en": "Start Tracking", "nl": "Begin met bijhouden", "fr": "Commencer le suivi"],

        // MARK: - Budget History
        "budget_history": ["en": "Budget History", "nl": "Budgetgeschiedenis", "fr": "Historique du budget"],
        "loading_history": ["en": "Loading history...", "nl": "Geschiedenis laden...", "fr": "Chargement de l'historique..."],
        "failed_load_history": ["en": "Failed to load history", "nl": "Geschiedenis laden mislukt", "fr": "Échec du chargement de l'historique"],
        "no_budget_history": ["en": "No Budget History", "nl": "Geen budgetgeschiedenis", "fr": "Aucun historique de budget"],
        "budget_history_appear": ["en": "Your budget history will appear here once you've set budgets for multiple months.", "nl": "Je budgetgeschiedenis verschijnt hier zodra je meerdere maanden een budget hebt ingesteld.", "fr": "Votre historique de budget apparaîtra ici une fois que vous aurez défini des budgets sur plusieurs mois."],
        "category_allocations": ["en": "Category Allocations", "nl": "Categorieverdeling", "fr": "Répartition par catégorie"],

        // MARK: - Edit Category Budgets
        "no_category_targets": ["en": "No category targets yet", "nl": "Nog geen categoriedoelen", "fr": "Pas encore d'objectifs par catégorie"],
        "add_category_target": ["en": "Add category target", "nl": "Categoriedoel toevoegen", "fr": "Ajouter un objectif de catégorie"],
        "independent_limits": ["en": "Independent limits — they don't need to add up to your monthly budget.", "nl": "Onafhankelijke limieten — ze hoeven niet op te tellen tot je maandbudget.", "fr": "Limites indépendantes — elles ne doivent pas correspondre à votre budget mensuel."],
        "edited": ["en": "Edited", "nl": "Bewerkt", "fr": "Modifié"],
        "deleted": ["en": "Deleted", "nl": "Verwijderd", "fr": "Supprimé"],

        // MARK: - Category Budget Detail
        "over_budget": ["en": "Over Budget", "nl": "Over budget", "fr": "Dépassement de budget"],
        "warning": ["en": "Warning", "nl": "Waarschuwing", "fr": "Attention"],
        "on_track": ["en": "On Track", "nl": "Op koers", "fr": "En bonne voie"],
        "needs_attention": ["en": "Needs Attention", "nl": "Aandacht nodig", "fr": "Attention requise"],
        "on_track_first": ["en": "On Track First", "nl": "Op koers eerst", "fr": "En bonne voie d'abord"],
        "by_group": ["en": "By Group", "nl": "Per groep", "fr": "Par groupe"],
        "a_z": ["en": "A-Z", "nl": "A-Z", "fr": "A-Z"],
        "over": ["en": "Over", "nl": "Over", "fr": "Dépassé"],
        "almost_at_limit": ["en": "Almost at limit", "nl": "Bijna aan limiet", "fr": "Presque à la limite"],
        "used": ["en": "used", "nl": "gebruikt", "fr": "utilisé"],
        "categories_found": ["en": "categories found", "nl": "categorieën gevonden", "fr": "catégories trouvées"],
        "see_all": ["en": "See All", "nl": "Bekijk alles", "fr": "Voir tout"],

        // MARK: - Receipts
        "receipt_details": ["en": "Receipt Details", "nl": "Kassaticketdetails", "fr": "Détails du ticket"],
        "duplicate_receipt": ["en": "Duplicate Receipt", "nl": "Dubbel kassaticket", "fr": "Ticket en double"],
        "duplicate_receipt_msg": ["en": "This receipt was already uploaded before. The items have not been added again.", "nl": "Dit kassaticket was al eerder geüpload. De items zijn niet opnieuw toegevoegd.", "fr": "Ce ticket a déjà été téléchargé. Les articles n'ont pas été ajoutés à nouveau."],
        "total": ["en": "Total", "nl": "Totaal", "fr": "Total"],
        "health_score": ["en": "Health Score", "nl": "Gezondheidsscore", "fr": "Score santé"],
        "split_with_friends": ["en": "Split with Friends", "nl": "Delen met vrienden", "fr": "Partager avec des amis"],
        "divide_receipt": ["en": "Divide this receipt among friends", "nl": "Verdeel dit kassaticket onder vrienden", "fr": "Répartir ce ticket entre amis"],
        "items": ["en": "Items", "nl": "Items", "fr": "Articles"],
        "no_items_found_receipt": ["en": "No items found", "nl": "Geen items gevonden", "fr": "Aucun article trouvé"],
        "no_items_detected": ["en": "The receipt was uploaded successfully, but no items were detected.", "nl": "Het kassaticket is succesvol geüpload, maar er zijn geen items gedetecteerd.", "fr": "Le ticket a été téléchargé avec succès, mais aucun article n'a été détecté."],
        "delete_receipt": ["en": "Delete Receipt", "nl": "Kassaticket verwijderen", "fr": "Supprimer le ticket"],
        "delete_receipt_confirm": ["en": "Are you sure you want to delete this receipt? This action cannot be undone.", "nl": "Ben je zeker dat je dit kassaticket wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.", "fr": "Êtes-vous sûr de vouloir supprimer ce ticket ? Cette action est irréversible."],
        "no_receipts": ["en": "No Receipts", "nl": "Geen kassatickets", "fr": "Aucun ticket"],
        "no_receipts_found": ["en": "No receipts found for this period", "nl": "Geen kassatickets gevonden voor deze periode", "fr": "Aucun ticket trouvé pour cette période"],
        "qty": ["en": "Qty", "nl": "Aantal", "fr": "Qté"],

        // MARK: - Receipt Scan
        "got_digital_receipt": ["en": "Got a digital receipt?", "nl": "Heb je een digitaal kassaticket?", "fr": "Vous avez un ticket digital ?"],
        "use_share_button": ["en": "Use the Share button from any app", "nl": "Gebruik de Deel-knop vanuit elke app", "fr": "Utilisez le bouton Partager depuis n'importe quelle app"],
        "wallet_pass_creator": ["en": "Wallet Pass Creator", "nl": "Wallet Pass Aanmaken", "fr": "Créer un pass Wallet"],
        "wallet_pass_desc": ["en": "Create Apple Wallet loyalty cards to receive digital receipts", "nl": "Maak Apple Wallet klantenkaarten aan om digitale kassatickets te ontvangen", "fr": "Créez des cartes de fidélité Apple Wallet pour recevoir des tickets digitaux"],
        "top_stores": ["en": "Top Stores", "nl": "Topwinkels", "fr": "Magasins principaux"],
        "top_categories": ["en": "Top Categories", "nl": "Topcategorieën", "fr": "Catégories principales"],
        "upload_limit_reached": ["en": "Upload Limit Reached", "nl": "Uploadlimiet bereikt", "fr": "Limite de téléchargement atteinte"],
        "upload_limit_month": ["en": "You've used all your receipt uploads for this month. Your limit will reset soon.", "nl": "Je hebt al je kassaticket-uploads voor deze maand opgebruikt. Je limiet wordt binnenkort hersteld.", "fr": "Vous avez utilisé tous vos téléchargements de tickets pour ce mois. Votre limite sera bientôt réinitialisée."],

        // MARK: - Receipt Upload / Camera
        "upload_receipt": ["en": "Upload Receipt", "nl": "Kassaticket uploaden", "fr": "Télécharger un ticket"],
        "uploading_receipt": ["en": "Uploading Receipt...", "nl": "Kassaticket uploaden...", "fr": "Téléchargement du ticket..."],
        "processing": ["en": "Processing...", "nl": "Verwerken...", "fr": "Traitement..."],
        "done_excl": ["en": "Done!", "nl": "Klaar!", "fr": "Terminé !"],
        "upload_failed": ["en": "Upload Failed", "nl": "Upload mislukt", "fr": "Échec du téléchargement"],
        "try_again": ["en": "Try Again", "nl": "Opnieuw proberen", "fr": "Réessayer"],
        "dismiss": ["en": "Dismiss", "nl": "Sluiten", "fr": "Fermer"],
        "processing_failed": ["en": "Processing Failed!", "nl": "Verwerking mislukt!", "fr": "Échec du traitement !"],
        "receipt_uploaded": ["en": "Receipt Uploaded!", "nl": "Kassaticket geüpload!", "fr": "Ticket téléchargé !"],
        "quality_check_failed": ["en": "Quality Check Failed", "nl": "Kwaliteitscontrole mislukt", "fr": "Échec du contrôle qualité"],
        "quality_score": ["en": "Quality Score:", "nl": "Kwaliteitsscore:", "fr": "Score de qualité :"],
        "minimum_required": ["en": "Minimum Required:", "nl": "Minimum vereist:", "fr": "Minimum requis :"],
        "tips": ["en": "Tips:", "nl": "Tips:", "fr": "Conseils :"],
        "ensure_good_lighting": ["en": "Ensure good lighting", "nl": "Zorg voor goede belichting", "fr": "Assurez un bon éclairage"],
        "hold_device_steady": ["en": "Hold device steady", "nl": "Houd je toestel stil", "fr": "Tenez l'appareil stable"],
        "capture_entire_receipt": ["en": "Capture entire receipt", "nl": "Leg het hele kassaticket vast", "fr": "Capturez l'intégralité du ticket"],
        "review": ["en": "Review", "nl": "Bekijken", "fr": "Vérifier"],
        "preparing_preview": ["en": "Preparing preview...", "nl": "Voorbeeld voorbereiden...", "fr": "Préparation de l'aperçu..."],
        "retake": ["en": "Retake", "nl": "Opnieuw nemen", "fr": "Reprendre"],
        "add_more": ["en": "Add More", "nl": "Meer toevoegen", "fr": "Ajouter plus"],

        // MARK: - Share Extension
        "preparing_upload": ["en": "Preparing to upload...", "nl": "Voorbereiden om te uploaden...", "fr": "Préparation du téléchargement..."],
        "uploading_receipts": ["en": "Uploading Receipts", "nl": "Kassatickets uploaden", "fr": "Téléchargement des tickets"],
        "uploaded": ["en": "uploaded", "nl": "geüpload", "fr": "téléchargé"],
        "receipt_failed": ["en": "Receipt Processing Failed!", "nl": "Verwerking van kassaticket mislukt!", "fr": "Échec du traitement du ticket !"],

        // MARK: - Expense Splitting
        "split_receipt": ["en": "Split Receipt", "nl": "Kassaticket delen", "fr": "Partager le ticket"],
        "friends": ["en": "Friends", "nl": "Vrienden", "fr": "Amis"],
        "add_friends_split": ["en": "Add friends to split with", "nl": "Voeg vrienden toe om mee te delen", "fr": "Ajoutez des amis pour partager"],
        "view_summary_share": ["en": "View Summary & Share", "nl": "Overzicht bekijken & delen", "fr": "Voir le résumé & partager"],
        "split_label": ["en": "Split:", "nl": "Verdeling:", "fr": "Répartition :"],
        "split_summary": ["en": "Split Summary", "nl": "Verdeelresultaat", "fr": "Résumé du partage"],
        "split_between": ["en": "Split between", "nl": "Verdeeld onder", "fr": "Réparti entre"],
        "person": ["en": "person", "nl": "persoon", "fr": "personne"],
        "people": ["en": "people", "nl": "personen", "fr": "personnes"],
        "share_split": ["en": "Share Split", "nl": "Verdeling delen", "fr": "Partager la répartition"],
        "split_transaction": ["en": "Split Transaction", "nl": "Transactie delen", "fr": "Partager la transaction"],
        "split_with": ["en": "Split with", "nl": "Verdeel met", "fr": "Partager avec"],
        "each_person_pays": ["en": "Each person pays", "nl": "Elke persoon betaalt", "fr": "Chaque personne paie"],
        "custom_split": ["en": "Custom split", "nl": "Aangepaste verdeling", "fr": "Répartition personnalisée"],
        "split_correct": ["en": "Split adds up correctly", "nl": "Verdeling klopt", "fr": "La répartition est correcte"],
        "fix": ["en": "Fix", "nl": "Corrigeren", "fr": "Corriger"],
        "add_friends_split_tap": ["en": "Add friends to split", "nl": "Voeg vrienden toe om te delen", "fr": "Ajoutez des amis pour partager"],
        "tap_plus_button": ["en": "Tap the + button above to add people to split this expense with.", "nl": "Tik op de + knop hierboven om mensen toe te voegen om deze uitgave mee te delen.", "fr": "Appuyez sur le bouton + ci-dessus pour ajouter des personnes avec qui partager cette dépense."],
        "done_editing": ["en": "Done Editing", "nl": "Klaar met bewerken", "fr": "Modification terminée"],
        "add_friend": ["en": "Add Friend", "nl": "Vriend toevoegen", "fr": "Ajouter un ami"],
        "add_friend_split": ["en": "Add a friend to split with", "nl": "Voeg een vriend toe om mee te delen", "fr": "Ajoutez un ami pour partager"],
        "recent_friends": ["en": "Recent Friends", "nl": "Recente vrienden", "fr": "Amis récents"],
        "friends_name": ["en": "Friend's name", "nl": "Naam van vriend", "fr": "Nom de l'ami"],

        // MARK: - Promotions
        "save_up_to": ["en": "Save up to", "nl": "Bespaar tot", "fr": "Économisez jusqu'à"],
        "total_savings_week": ["en": "TOTAL SAVINGS THIS WEEK", "nl": "TOTALE BESPARING DEZE WEEK", "fr": "ÉCONOMIES TOTALES CETTE SEMAINE"],
        "valid": ["en": "Valid", "nl": "Geldig", "fr": "Valable"],
        "view_in_folder": ["en": "View in folder", "nl": "Bekijk in folder", "fr": "Voir dans le dépliant"],
        "smart_switch": ["en": "SMART SWITCH", "nl": "SLIMME WISSEL", "fr": "CHANGEMENT MALIN"],
        "best_value_store": ["en": "Best value", "nl": "Beste keuze", "fr": "Meilleur rapport qualité-prix"],
        "no_deals_week": ["en": "No deals this week", "nl": "Geen aanbiedingen deze week", "fr": "Aucune promotion cette semaine"],
        "keep_scanning": ["en": "Keep scanning receipts so we can find personalized deals for you", "nl": "Blijf kassatickets scannen zodat we gepersonaliseerde aanbiedingen voor je kunnen vinden", "fr": "Continuez à scanner vos tickets pour que nous puissions trouver des promotions personnalisées"],
        "couldnt_load_deals": ["en": "Couldn't load deals", "nl": "Aanbiedingen laden mislukt", "fr": "Impossible de charger les promotions"],
        "sniffing_deals": ["en": "Sniffing out your deals...", "nl": "Je aanbiedingen opsnuiven...", "fr": "On renifle vos promotions..."],
        "checking_promos": ["en": "Checking promotions across stores", "nl": "Promoties controleren in alle winkels", "fr": "Vérification des promotions dans les magasins"],
        "finding_promotions": ["en": "Finding promotions", "nl": "Promoties zoeken", "fr": "Recherche de promotions"],

        // MARK: - Insights
        "daily_insight": ["en": "Daily Insight", "nl": "Dagelijks inzicht", "fr": "Analyse du jour"],
        "generating_insight": ["en": "Generating insight...", "nl": "Inzicht genereren...", "fr": "Génération de l'analyse..."],
        "insight_by_milo": ["en": "Insight by Milo", "nl": "Inzicht door Milo", "fr": "Analyse par Milo"],

        // MARK: - Subscription Banner
        "unlock_premium": ["en": "Unlock Premium", "nl": "Ontgrendel Premium", "fr": "Débloquer Premium"],
        "start_free_trial_banner": ["en": "Start your 14-day free trial", "nl": "Start je 14 dagen gratis proefperiode", "fr": "Commencez votre essai gratuit de 14 jours"],
        "try_free": ["en": "Try Free", "nl": "Probeer gratis", "fr": "Essayer gratuitement"],
        "premium_active": ["en": "Premium Active", "nl": "Premium actief", "fr": "Premium actif"],
        "upgrade_premium": ["en": "Upgrade to Premium", "nl": "Upgrade naar Premium", "fr": "Passer à Premium"],
        "unlock_all_features": ["en": "Unlock all features with a free trial", "nl": "Ontgrendel alle functies met een gratis proefperiode", "fr": "Débloquez toutes les fonctionnalités avec un essai gratuit"],
        "premium_feature": ["en": "Premium Feature", "nl": "Premiumfunctie", "fr": "Fonctionnalité Premium"],
        "unlock": ["en": "Unlock", "nl": "Ontgrendelen", "fr": "Débloquer"],
        "upgrade_unlimited": ["en": "Upgrade for unlimited uploads", "nl": "Upgrade voor onbeperkt uploaden", "fr": "Passez à Premium pour des téléchargements illimités"],

        // MARK: - Health Score
        "no_data": ["en": "No Data", "nl": "Geen gegevens", "fr": "Aucune donnée"],
        "upload_receipts_health": ["en": "Upload receipts to see your health score", "nl": "Upload kassatickets om je gezondheidsscore te zien", "fr": "Téléchargez des tickets pour voir votre score santé"],
        "na": ["en": "N/A", "nl": "N/B", "fr": "N/D"],
        "vs_last_period": ["en": "vs last period", "nl": "vs vorige periode", "fr": "vs période précédente"],
        "this_month": ["en": "This Month", "nl": "Deze maand", "fr": "Ce mois"],
        "last_month": ["en": "Last Month", "nl": "Vorige maand", "fr": "Mois dernier"],

        // MARK: - Transactions
        "transactions": ["en": "Transactions", "nl": "Transacties", "fr": "Transactions"],
        "total_amount": ["en": "Total Amount", "nl": "Totaalbedrag", "fr": "Montant total"],
        "total_transactions": ["en": "Total Transactions", "nl": "Totaal transacties", "fr": "Total des transactions"],
        "date": ["en": "Date", "nl": "Datum", "fr": "Date"],
        "item": ["en": "Item", "nl": "Item", "fr": "Article"],
        "amount": ["en": "Amount", "nl": "Bedrag", "fr": "Montant"],
        "no_transactions": ["en": "No transactions", "nl": "Geen transacties", "fr": "Aucune transaction"],
        "total_spent": ["en": "Total Spent", "nl": "Totaal uitgegeven", "fr": "Total dépensé"],
        "by_category": ["en": "By Category", "nl": "Per categorie", "fr": "Par catégorie"],
        "spending_breakdown": ["en": "Spending Breakdown", "nl": "Uitgavenverdeling", "fr": "Répartition des dépenses"],
        "loading_breakdown": ["en": "Loading breakdown...", "nl": "Verdeling laden...", "fr": "Chargement de la répartition..."],

        // MARK: - Search
        "search_items": ["en": "Search Items", "nl": "Zoek items", "fr": "Rechercher des articles"],
        "no_results_search": ["en": "No Results", "nl": "Geen resultaten", "fr": "Aucun résultat"],
        "try_adjusting_search": ["en": "Try adjusting your search", "nl": "Probeer je zoekopdracht aan te passen", "fr": "Essayez de modifier votre recherche"],
        "groceries": ["en": "Groceries", "nl": "Boodschappen", "fr": "Courses"],

        // MARK: - Year in Review
        "no_spending_data_for": ["en": "No spending data for", "nl": "Geen uitgavegegevens voor", "fr": "Aucune donnée de dépenses pour"],
        "monthly_breakdown": ["en": "Monthly Breakdown", "nl": "Maandelijks overzicht", "fr": "Répartition mensuelle"],

        // MARK: - Wallet Pass
        "select_barcode": ["en": "Select the barcode you want to use", "nl": "Selecteer de barcode die je wilt gebruiken", "fr": "Sélectionnez le code-barres à utiliser"],
        "scan_barcode_below": ["en": "Scan barcode below", "nl": "Scan barcode hieronder", "fr": "Scannez le code-barres ci-dessous"],
        "barcode_captured": ["en": "Barcode captured", "nl": "Barcode vastgelegd", "fr": "Code-barres capturé"],
        "rescan": ["en": "Rescan", "nl": "Opnieuw scannen", "fr": "Scanner à nouveau"],
        "enter_manually": ["en": "Enter manually", "nl": "Handmatig invoeren", "fr": "Saisir manuellement"],
        "detecting_barcode": ["en": "Detecting barcode...", "nl": "Barcode detecteren...", "fr": "Détection du code-barres..."],
        "creating_pass": ["en": "Creating Pass...", "nl": "Pas aanmaken...", "fr": "Création du pass..."],
        "pass_preview": ["en": "Pass Preview", "nl": "Pas voorbeeld", "fr": "Aperçu du pass"],
        "pass_preview_desc": ["en": "This is how your loyalty card will appear in Apple Wallet", "nl": "Zo zal je klantenkaart eruitzien in Apple Wallet", "fr": "Voici comment votre carte de fidélité apparaîtra dans Apple Wallet"],
        "pass_created": ["en": "Pass Created!", "nl": "Pas aangemaakt!", "fr": "Pass créé !"],
        "coming_soon": ["en": "Coming Soon", "nl": "Binnenkort beschikbaar", "fr": "Bientôt disponible"],
        "position_barcode": ["en": "Position barcode within frame", "nl": "Positioneer barcode in het kader", "fr": "Positionnez le code-barres dans le cadre"],
        "barcode_detected": ["en": "Barcode Detected!", "nl": "Barcode gedetecteerd!", "fr": "Code-barres détecté !"],

        // MARK: - Saved Receipts
        "saved_receipts": ["en": "Saved Receipts", "nl": "Opgeslagen kassatickets", "fr": "Tickets enregistrés"],
        "all_cloud_based": ["en": "All Receipts Are Cloud-Based", "nl": "Alle kassatickets zijn in de cloud", "fr": "Tous les tickets sont dans le cloud"],
        "cloud_based_desc": ["en": "Receipts are now automatically uploaded to the cloud when you scan them. Local storage has been disabled.", "nl": "Kassatickets worden nu automatisch naar de cloud geüpload wanneer je ze scant. Lokale opslag is uitgeschakeld.", "fr": "Les tickets sont maintenant automatiquement téléchargés dans le cloud quand vous les scannez. Le stockage local a été désactivé."],
        "automatic_backup": ["en": "Automatic cloud backup", "nl": "Automatische cloudback-up", "fr": "Sauvegarde cloud automatique"],
        "access_any_device": ["en": "Access from any device", "nl": "Toegang vanaf elk apparaat", "fr": "Accès depuis n'importe quel appareil"],
        "automatic_processing": ["en": "Automatic processing", "nl": "Automatische verwerking", "fr": "Traitement automatique"],

        // MARK: - Rate Limit Messages
        "messages": ["en": "messages", "nl": "berichten", "fr": "messages"],
        "message_limit_period": ["en": "Message limit reached for this period.", "nl": "Berichtlimiet bereikt voor deze periode.", "fr": "Limite de messages atteinte pour cette période."],
        "message_limit_resets": ["en": "Message limit reached. Resets", "nl": "Berichtlimiet bereikt. Herstelt", "fr": "Limite de messages atteinte. Réinitialisation"],
        "no_receipts_remaining": ["en": "No receipts remaining", "nl": "Geen kassatickets meer over", "fr": "Aucun ticket restant"],
        "one_receipt_remaining": ["en": "1 receipt remaining", "nl": "1 kassaticket over", "fr": "1 ticket restant"],
        "receipts_remaining": ["en": "receipts remaining", "nl": "kassatickets over", "fr": "tickets restants"],
        "upload_limit_period": ["en": "Upload limit reached for this period.", "nl": "Uploadlimiet bereikt voor deze periode.", "fr": "Limite de téléchargement atteinte pour cette période."],
        "resets_today": ["en": "Resets today", "nl": "Herstelt vandaag", "fr": "Réinitialisation aujourd'hui"],
        "resets_in_1_day": ["en": "Resets in 1 day", "nl": "Herstelt in 1 dag", "fr": "Réinitialisation dans 1 jour"],

        // MARK: - Expandable Receipt Card
        "store_receipt": ["en": "store", "nl": "winkel", "fr": "magasin"],
        "stores_count": ["en": "stores", "nl": "winkels", "fr": "magasins"],

        // MARK: - Budget Ring
        "under_budget": ["en": "Under budget", "nl": "Onder budget", "fr": "Sous le budget"],
        "over_budget_projection": ["en": "Over budget projection", "nl": "Over budget projectie", "fr": "Projection de dépassement"],
        "already_over_budget": ["en": "Already over budget", "nl": "Al over budget", "fr": "Budget déjà dépassé"],

        // MARK: - Subscription Banner (extra)
        "pro": ["en": "Pro", "nl": "Pro", "fr": "Pro"],
        "manage": ["en": "Manage", "nl": "Beheren", "fr": "Gérer"],

        // MARK: - Insight Button (extra)
        "daily_spending_insight": ["en": "Daily Spending Insight", "nl": "Dagelijks uitgave-inzicht", "fr": "Analyse quotidienne des dépenses"],
        "daily_health_insight": ["en": "Daily Health Insight", "nl": "Dagelijks gezondheidsinzicht", "fr": "Analyse quotidienne santé"],

        // MARK: - Donut Chart / Category Detail
        "avg_price": ["en": "AVG PRICE", "nl": "GEM. PRIJS", "fr": "PRIX MOYEN"],
        "per_item": ["en": "per item", "nl": "per stuk", "fr": "par article"],
        "items_purchased": ["en": "items purchased", "nl": "items gekocht", "fr": "articles achetés"],
        "others": ["en": "Others", "nl": "Andere", "fr": "Autres"],
        "of_total": ["en": "of total", "nl": "van totaal", "fr": "du total"],
        "edit_items": ["en": "Edit Items", "nl": "Items bewerken", "fr": "Modifier les articles"],

        // MARK: - Year In Review (extra)
        "total_receipts": ["en": "Total Receipts", "nl": "Totaal kassatickets", "fr": "Total des tickets"],
        "total_spent_year": ["en": "Total Spent", "nl": "Totaal uitgegeven", "fr": "Total dépensé"],
        "avg_per_receipt": ["en": "Avg Per Receipt", "nl": "Gem. per kassaticket", "fr": "Moy. par ticket"],
        "avg_per_month": ["en": "Avg Per Month", "nl": "Gem. per maand", "fr": "Moy. par mois"],
        "top_store": ["en": "Top Store", "nl": "Favoriete winkel", "fr": "Magasin principal"],
        "top_category": ["en": "Top Category", "nl": "Topcategorie", "fr": "Catégorie principale"],
        "biggest_receipt": ["en": "Biggest Receipt", "nl": "Grootste kassaticket", "fr": "Plus gros ticket"],
        "smallest_receipt": ["en": "Smallest Receipt", "nl": "Kleinste kassaticket", "fr": "Plus petit ticket"],

        // MARK: - Store Detail
        "store_detail": ["en": "Store Details", "nl": "Winkeldetails", "fr": "Détails du magasin"],
        "store_breakdown": ["en": "Store Breakdown", "nl": "Winkeloverzicht", "fr": "Répartition par magasin"],
        "total_visits": ["en": "Total Visits", "nl": "Totaal bezoeken", "fr": "Total des visites"],
        "avg_per_visit": ["en": "Avg Per Visit", "nl": "Gem. per bezoek", "fr": "Moy. par visite"],
        "recent_receipts": ["en": "Recent Receipts", "nl": "Recente kassatickets", "fr": "Tickets récents"],
        "view_all_receipts": ["en": "View All Receipts", "nl": "Bekijk alle kassatickets", "fr": "Voir tous les tickets"],
        "all_time": ["en": "All Time", "nl": "Alle tijd", "fr": "Depuis toujours"],
        "stores_all_time": ["en": "stores all time", "nl": "winkels alle tijd", "fr": "magasins depuis toujours"],
        "stores_this_year": ["en": "stores this year", "nl": "winkels dit jaar", "fr": "magasins cette année"],
        "categories_all_time": ["en": "categories all time", "nl": "categorieën alle tijd", "fr": "catégories depuis toujours"],
        "categories_this_year": ["en": "categories this year", "nl": "categorieën dit jaar", "fr": "catégories cette année"],
        "category_singular": ["en": "category", "nl": "categorie", "fr": "catégorie"],
        "categories_count": ["en": "categories", "nl": "categorieën", "fr": "catégories"],
        "no_items_in_period": ["en": "No items in this period", "nl": "Geen items in deze periode", "fr": "Aucun article pour cette période"],
        "receipt_singular": ["en": "receipt", "nl": "kassaticket", "fr": "ticket"],
        "receipt_plural": ["en": "receipts", "nl": "kassatickets", "fr": "tickets"],
        "show_less": ["en": "Show Less", "nl": "Minder tonen", "fr": "Voir moins"],
        "show_all": ["en": "Show All", "nl": "Alles tonen", "fr": "Voir tout"],
        "no_receipts_for_store": ["en": "No receipts for this store", "nl": "Geen kassatickets voor deze winkel", "fr": "Aucun ticket pour ce magasin"],
        "store_singular": ["en": "store", "nl": "winkel", "fr": "magasin"],
        "store_plural": ["en": "stores", "nl": "winkels", "fr": "magasins"],

        // MARK: - Wallet Pass (extra)
        "loyalty_card": ["en": "Loyalty Card", "nl": "Klantenkaart", "fr": "Carte de fidélité"],
        "add_to_wallet": ["en": "Add to Wallet", "nl": "Voeg toe aan Wallet", "fr": "Ajouter au Wallet"],
        "scan_loyalty_card": ["en": "Scan loyalty card", "nl": "Scan klantenkaart", "fr": "Scanner la carte de fidélité"],
        "enter_barcode": ["en": "Enter Barcode", "nl": "Voer barcode in", "fr": "Saisir le code-barres"],
        "barcode_number": ["en": "Barcode Number", "nl": "Barcodenummer", "fr": "Numéro du code-barres"],
        "create_pass": ["en": "Create Pass", "nl": "Pas aanmaken", "fr": "Créer le pass"],
        "select_store": ["en": "Select Store", "nl": "Selecteer winkel", "fr": "Sélectionner le magasin"],
        "preview": ["en": "Preview", "nl": "Voorbeeld", "fr": "Aperçu"],
        "multiple_barcodes_found": ["en": "Multiple Barcodes Found", "nl": "Meerdere barcodes gevonden", "fr": "Plusieurs codes-barres trouvés"],
        "select_barcode_to_use": ["en": "Select the barcode you want to use", "nl": "Selecteer de barcode die je wilt gebruiken", "fr": "Sélectionnez le code-barres à utiliser"],
        "an_error_occurred": ["en": "An error occurred", "nl": "Er is een fout opgetreden", "fr": "Une erreur s'est produite"],
        "store_name": ["en": "Store Name", "nl": "Winkelnaam", "fr": "Nom du magasin"],
        "store_details": ["en": "Store Details", "nl": "Winkeldetails", "fr": "Détails du magasin"],
        "loyalty_card_barcode": ["en": "Loyalty Card Barcode", "nl": "Klantenkaart barcode", "fr": "Code-barres carte de fidélité"],
        "scan": ["en": "Scan", "nl": "Scan", "fr": "Scanner"],
        "take_photo": ["en": "Take a photo", "nl": "Neem een foto", "fr": "Prendre une photo"],
        "upload": ["en": "Upload", "nl": "Upload", "fr": "Télécharger"],
        "from_photos": ["en": "From Photos", "nl": "Uit foto's", "fr": "Depuis les photos"],
        "enter_barcode_value": ["en": "Enter barcode value", "nl": "Voer barcodewaarde in", "fr": "Saisir la valeur du code-barres"],
        "pass_color": ["en": "Pass Color", "nl": "Paskleur", "fr": "Couleur du pass"],
        "store_logo": ["en": "Store Logo", "nl": "Winkellogo", "fr": "Logo du magasin"],
        "change_logo": ["en": "Change Logo", "nl": "Logo wijzigen", "fr": "Changer le logo"],
        "add_logo": ["en": "Add Logo", "nl": "Logo toevoegen", "fr": "Ajouter un logo"],
        "optional_pass_header": ["en": "Optional - appears in the pass header", "nl": "Optioneel - verschijnt in de paskoptekst", "fr": "Facultatif - apparaît dans l'en-tête du pass"],
        "pass_preview_description": ["en": "This is how your loyalty card will appear in Apple Wallet", "nl": "Zo zal je klantenkaart eruitzien in Apple Wallet", "fr": "Voici comment votre carte de fidélité apparaîtra dans Apple Wallet"],
        "your": ["en": "Your", "nl": "Je", "fr": "Votre"],
        "loyalty_card_ready": ["en": "loyalty card is ready", "nl": "klantenkaart is klaar", "fr": "carte de fidélité est prête"],
        "wallet_integration_coming_soon": ["en": "Apple Wallet integration coming soon", "nl": "Apple Wallet-integratie binnenkort beschikbaar", "fr": "Intégration Apple Wallet bientôt disponible"],

        // MARK: - Barcode Camera
        "position_barcode_within_frame": ["en": "Position barcode within frame", "nl": "Positioneer barcode in het kader", "fr": "Positionnez le code-barres dans le cadre"],
        "qr_barcodes_loyalty_cards": ["en": "QR codes, barcodes & loyalty cards", "nl": "QR-codes, barcodes & klantenkaarten", "fr": "Codes QR, codes-barres & cartes de fidélité"],
        "tap_to_capture_or_autodetect": ["en": "Tap to capture or auto-detect", "nl": "Tik om vast te leggen of auto-detectie", "fr": "Appuyez pour capturer ou auto-détection"],

        // MARK: - Year in Review (singular/plural)
        "transaction_singular": ["en": "transaction", "nl": "transactie", "fr": "transaction"],
        "transaction_plural": ["en": "transactions", "nl": "transacties", "fr": "transactions"],

        // MARK: - Subscription Banner (variant keys)
        "start_14day_trial": ["en": "Start your 14-day free trial", "nl": "Start je 14 dagen gratis proefperiode", "fr": "Commencez votre essai gratuit de 14 jours"],
        "unlock_features_trial": ["en": "Unlock all features with a free trial", "nl": "Ontgrendel alle functies met een gratis proefperiode", "fr": "Débloquez toutes les fonctionnalités avec un essai gratuit"],
        "upgrade_unlimited_uploads": ["en": "Upgrade for unlimited uploads", "nl": "Upgrade voor onbeperkt uploaden", "fr": "Passez à Premium pour des téléchargements illimités"],

        // MARK: - Camera
        "normal": ["en": "Normal", "nl": "Normaal", "fr": "Normal"],
        "long_receipt": ["en": "Long Receipt", "nl": "Lang kassaticket", "fr": "Ticket long"],

        // MARK: - Category Groups
        "group_fresh_food": ["en": "Fresh Food", "nl": "Vers voedsel", "fr": "Produits frais"],
        "group_pantry_staples": ["en": "Pantry & Staples", "nl": "Voorraadkast", "fr": "Garde-manger"],
        "group_frozen": ["en": "Frozen", "nl": "Diepvries", "fr": "Surgelés"],
        "group_drinks": ["en": "Drinks", "nl": "Dranken", "fr": "Boissons"],
        "group_snacks": ["en": "Snacks", "nl": "Snacks", "fr": "Snacks"],
        "group_household": ["en": "Household", "nl": "Huishouden", "fr": "Ménage"],
        "group_personal_care": ["en": "Personal Care", "nl": "Persoonlijke verzorging", "fr": "Soins personnels"],
        "group_other": ["en": "Other", "nl": "Andere", "fr": "Autres"],

        // MARK: - Category Display Names
        "cat_fruits": ["en": "Fruits", "nl": "Fruit", "fr": "Fruits"],
        "cat_vegetables": ["en": "Vegetables", "nl": "Groenten", "fr": "Légumes"],
        "cat_meat_poultry": ["en": "Meat & Poultry", "nl": "Vlees & Gevogelte", "fr": "Viande & Volaille"],
        "cat_charcuterie_salads": ["en": "Charcuterie & Salads", "nl": "Charcuterie & Salades", "fr": "Charcuterie & Salades"],
        "cat_fish_seafood": ["en": "Fish & Seafood", "nl": "Vis & Zeevruchten", "fr": "Poisson & Fruits de mer"],
        "cat_dairy_eggs_cheese": ["en": "Dairy, Eggs & Cheese", "nl": "Zuivel, Eieren & Kaas", "fr": "Produits laitiers, Œufs & Fromage"],
        "cat_bakery": ["en": "Bakery", "nl": "Bakkerij", "fr": "Boulangerie"],
        "cat_pastries": ["en": "Pastries", "nl": "Gebak", "fr": "Pâtisseries"],
        "cat_grains_pasta_potatoes": ["en": "Grains, Pasta & Potatoes", "nl": "Granen, Pasta & Aardappelen", "fr": "Céréales, Pâtes & Pommes de terre"],
        "cat_canned_jarred": ["en": "Canned & Jarred Goods", "nl": "Conserven & Bokalen", "fr": "Conserves & Bocaux"],
        "cat_sauces_condiments": ["en": "Sauces & Condiments", "nl": "Sauzen & Specerijen", "fr": "Sauces & Condiments"],
        "cat_breakfast_cereal": ["en": "Breakfast & Cereal", "nl": "Ontbijt & Granen", "fr": "Petit-déjeuner & Céréales"],
        "cat_baking_flour": ["en": "Baking & Flour", "nl": "Bakbenodigdheden & Bloem", "fr": "Pâtisserie & Farine"],
        "cat_frozen_ingredients": ["en": "Frozen Ingredients", "nl": "Diepvriesgroenten & -fruit", "fr": "Ingrédients surgelés"],
        "cat_fries_snacks": ["en": "Fries & Snacks", "nl": "Frieten & Snacks", "fr": "Frites & Snacks"],
        "cat_ready_meals": ["en": "Ready Meals & Pizza", "nl": "Kant-en-klaar & Pizza", "fr": "Plats préparés & Pizza"],
        "cat_water": ["en": "Water", "nl": "Water", "fr": "Eau"],
        "cat_soda_juices": ["en": "Soda & Juices", "nl": "Frisdranken & Sappen", "fr": "Sodas & Jus"],
        "cat_coffee_tea": ["en": "Coffee & Tea", "nl": "Koffie & Thee", "fr": "Café & Thé"],
        "cat_alcohol": ["en": "Alcohol", "nl": "Alcohol", "fr": "Alcool"],
        "cat_chips_nuts": ["en": "Chips, Nuts & Aperitif", "nl": "Chips, Noten & Aperitief", "fr": "Chips, Noix & Apéritif"],
        "cat_chocolate_sweets": ["en": "Chocolate, Biscuits & Sweets", "nl": "Chocolade, Koeken & Snoep", "fr": "Chocolat, Biscuits & Confiseries"],
        "cat_waste_bags": ["en": "Waste Bags", "nl": "Vuilniszakken", "fr": "Sacs poubelle"],
        "cat_cleaning": ["en": "Cleaning & Paper Goods", "nl": "Schoonmaak & Papier", "fr": "Nettoyage & Papier"],
        "cat_pharmacy_hygiene": ["en": "Pharmacy & Hygiene", "nl": "Apotheek & Hygiëne", "fr": "Pharmacie & Hygiène"],
        "cat_baby_kids": ["en": "Baby & Kids", "nl": "Baby & Kinderen", "fr": "Bébé & Enfants"],
        "cat_pet_supplies": ["en": "Pet Supplies", "nl": "Huisdierbenodigdheden", "fr": "Animaux domestiques"],
        "cat_tobacco": ["en": "Tobacco", "nl": "Tabak", "fr": "Tabac"],
        "cat_lottery": ["en": "Lottery & Scratch Cards", "nl": "Lotto & Krasloten", "fr": "Loterie & Tickets à gratter"],
        "cat_promos_discounts": ["en": "Promos & Discounts", "nl": "Promo's & Kortingen", "fr": "Promos & Réductions"],
        "cat_deposits": ["en": "Deposits", "nl": "Statiegeld", "fr": "Consignes"],
        "cat_other": ["en": "Other", "nl": "Andere", "fr": "Autres"],
    ]
}
