//
//  AppStrings.swift
//  Scandalicious
//
//  Central localization dictionary for all user-facing strings.
//  Keys map to [languageCode: translatedString].
//

import Foundation

enum AppStrings {
    // [key: [languageCode: translation]]
    static let strings: [String: [String: String]] = [

        // MARK: - Common
        "ok": ["en": "OK", "nl": "OK"],
        "cancel": ["en": "Cancel", "nl": "Annuleren"],
        "done": ["en": "Done", "nl": "Klaar"],
        "error": ["en": "Error", "nl": "Fout"],
        "save": ["en": "Save", "nl": "Opslaan"],
        "delete": ["en": "Delete", "nl": "Verwijderen"],
        "retry": ["en": "Retry", "nl": "Opnieuw proberen"],
        "edit": ["en": "Edit", "nl": "Bewerken"],
        "loading": ["en": "Loading...", "nl": "Laden..."],
        "unknown_error": ["en": "An unknown error occurred", "nl": "Er is een onbekende fout opgetreden"],
        "success": ["en": "Success", "nl": "Geslaagd"],
        "or": ["en": "OR", "nl": "OF"],

        // MARK: - Login / Auth
        "welcome_to_milo": ["en": "Welcome to Milo", "nl": "Welkom bij Milo"],
        "create_account": ["en": "Create your account", "nl": "Maak je account aan"],
        "sign_in_continue": ["en": "Sign in to continue", "nl": "Meld je aan om verder te gaan"],
        "email": ["en": "Email", "nl": "E-mail"],
        "password": ["en": "Password", "nl": "Wachtwoord"],
        "sign_up": ["en": "Sign Up", "nl": "Registreren"],
        "sign_in": ["en": "Sign In", "nl": "Aanmelden"],
        "sign_out": ["en": "Sign Out", "nl": "Afmelden"],
        "forgot_password": ["en": "Forgot Password?", "nl": "Wachtwoord vergeten?"],
        "continue_google": ["en": "Continue with Google", "nl": "Ga verder met Google"],
        "reset_password": ["en": "Reset Password", "nl": "Wachtwoord herstellen"],
        "send_reset_link": ["en": "Send Reset Link", "nl": "Verstuur herstelkoppeling"],
        "enter_email_reset": ["en": "Enter your email address to receive a password reset link.", "nl": "Voer je e-mailadres in om een herstellink te ontvangen."],
        "dont_have_account_signup": ["en": "Don't have an account? **Sign Up**", "nl": "Nog geen account? **Registreren**"],
        "already_have_account_signin": ["en": "Already have an account? **Sign In**", "nl": "Al een account? **Aanmelden**"],
        "password_reset_sent": ["en": "Password reset email sent!", "nl": "E-mail voor wachtwoordherstel verstuurd!"],
        "sign_out_confirm": ["en": "Are you sure you want to sign out?", "nl": "Ben je zeker dat je wilt afmelden?"],

        // MARK: - Onboarding
        "welcome": ["en": "Welcome", "nl": "Welkom"],
        "personalize_experience": ["en": "Let's personalize your experience", "nl": "Laten we je ervaring personaliseren"],
        "nickname": ["en": "Nickname", "nl": "Bijnaam"],
        "age": ["en": "Age", "nl": "Leeftijd"],
        "get_started": ["en": "Get Started", "nl": "Aan de slag"],

        // MARK: - Gender
        "gender_male": ["en": "Male", "nl": "Man"],
        "gender_female": ["en": "Female", "nl": "Vrouw"],
        "gender_x": ["en": "X", "nl": "X"],

        // MARK: - Paywall
        "meet_milo": ["en": "Meet Milo", "nl": "Maak kennis met Milo"],
        "your_ai_assistant": ["en": "Your AI shopping assistant", "nl": "Je AI-winkelassistent"],
        "feature_scan": ["en": "Scan", "nl": "Scan"],
        "feature_analyze": ["en": "Analyze", "nl": "Analyseer"],
        "feature_health": ["en": "Health", "nl": "Gezondheid"],
        "feature_chat": ["en": "Chat", "nl": "Chat"],
        "yearly": ["en": "Yearly", "nl": "Jaarlijks"],
        "monthly": ["en": "Monthly", "nl": "Maandelijks"],
        "year": ["en": "year", "nl": "jaar"],
        "month": ["en": "month", "nl": "maand"],
        "best_value": ["en": "BEST VALUE", "nl": "BESTE KEUZE"],
        "start_free_trial": ["en": "Start 14-Day Free Trial", "nl": "Start 14 dagen gratis proefperiode"],
        "restore_purchases": ["en": "Restore Purchases", "nl": "Aankopen herstellen"],
        "terms": ["en": "Terms", "nl": "Voorwaarden"],
        "privacy": ["en": "Privacy", "nl": "Privacy"],
        "cancel_anytime": ["en": "Cancel anytime. Auto-renews until canceled.", "nl": "Annuleer wanneer je wilt. Verlengt automatisch tot annulering."],
        "welcome_success": ["en": "Welcome!", "nl": "Welkom!"],

        // MARK: - ContentView / Tabs
        "tab_budget": ["en": "Budget", "nl": "Budget"],
        "tab_home": ["en": "Home", "nl": "Home"],
        "tab_milo": ["en": "Milo", "nl": "Milo"],
        "syncing": ["en": "Syncing", "nl": "Synchroniseren"],
        "synced": ["en": "Synced", "nl": "Gesynchroniseerd"],

        // MARK: - Profile
        "profile": ["en": "Profile", "nl": "Profiel"],
        "personal_information": ["en": "Personal Information", "nl": "Persoonlijke gegevens"],
        "language": ["en": "Language", "nl": "Taal"],
        "not_set": ["en": "Not set", "nl": "Niet ingesteld"],
        "saving": ["en": "Saving...", "nl": "Opslaan..."],
        "save_changes": ["en": "Save Changes", "nl": "Wijzigingen opslaan"],
        "account": ["en": "Account", "nl": "Account"],
        "not_available": ["en": "Not available", "nl": "Niet beschikbaar"],
        "current_plan": ["en": "Current Plan", "nl": "Huidig abonnement"],
        "renews_on": ["en": "Renews On", "nl": "Verlengt op"],
        "trial_ends": ["en": "Trial Ends", "nl": "Proefperiode eindigt"],
        "manage_subscription": ["en": "Manage Subscription", "nl": "Abonnement beheren"],
        "subscription": ["en": "Subscription", "nl": "Abonnement"],
        "insights": ["en": "Insights", "nl": "Inzichten"],
        "year_in_review": ["en": "Year in Review", "nl": "Jaaroverzicht"],
        "profile_updated": ["en": "Your profile has been updated successfully", "nl": "Je profiel is succesvol bijgewerkt"],
        "expired": ["en": "Expired", "nl": "Verlopen"],
        "free": ["en": "Free", "nl": "Gratis"],
        "premium_yearly": ["en": "Premium Yearly", "nl": "Premium Jaarlijks"],
        "premium_monthly": ["en": "Premium Monthly", "nl": "Premium Maandelijks"],
        "premium_yearly_trial": ["en": "Premium Yearly (Trial)", "nl": "Premium Jaarlijks (Proef)"],
        "premium_monthly_trial": ["en": "Premium Monthly (Trial)", "nl": "Premium Maandelijks (Proef)"],

        // MARK: - Overview
        "stores": ["en": "Stores", "nl": "Winkels"],
        "categories": ["en": "Categories", "nl": "Categorieën"],
        "failed_load_data": ["en": "Failed to load data", "nl": "Laden van gegevens mislukt"],
        "failed_load_items": ["en": "Failed to load items", "nl": "Laden van items mislukt"],
        "no_items_found": ["en": "No items found", "nl": "Geen items gevonden"],
        "receipts": ["en": "Receipts", "nl": "Kassatickets"],
        "scan_first_receipt": ["en": "Scan your first receipt to get started", "nl": "Scan je eerste kassaticket om te beginnen"],
        "no_receipts_period": ["en": "No receipts for this period", "nl": "Geen kassatickets voor deze periode"],
        "deleting": ["en": "Deleting...", "nl": "Verwijderen..."],
        "delete_failed": ["en": "Delete Failed", "nl": "Verwijderen mislukt"],
        "spent_this_month": ["en": "SPENT THIS MONTH", "nl": "UITGEGEVEN DEZE MAAND"],
        "no_category_data": ["en": "No category data", "nl": "Geen categoriegegevens"],
        "tap_to_flip_back": ["en": "Tap to flip back", "nl": "Tik om terug te draaien"],
        "tap_to_flip": ["en": "Tap to flip", "nl": "Tik om te draaien"],
        "sort_by": ["en": "Sort By", "nl": "Sorteer op"],
        "filters": ["en": "Filters", "nl": "Filters"],
        "nutri_score": ["en": "NUTRI SCORE", "nl": "NUTRI SCORE"],
        "all_stores": ["en": "All Stores", "nl": "Alle winkels"],
        "highest_spend": ["en": "Highest Spend", "nl": "Hoogste uitgave"],
        "lowest_spend": ["en": "Lowest Spend", "nl": "Laagste uitgave"],
        "store_name_sort": ["en": "Store Name", "nl": "Winkelnaam"],
        "tap_for_stores": ["en": "Tap for stores", "nl": "Tik voor winkels"],
        "tap_for_categories": ["en": "Tap for categories", "nl": "Tik voor categorieën"],
        "no_stores_yet": ["en": "No stores yet", "nl": "Nog geen winkels"],
        "no_categories_yet": ["en": "No categories yet", "nl": "Nog geen categorieën"],
        "visits": ["en": "visits", "nl": "bezoeken"],
        "spent": ["en": "spent", "nl": "uitgegeven"],
        "shopping_insights": ["en": "Shopping Insights", "nl": "Winkelinzichten"],

        // MARK: - Milo AI Chat
        "milo": ["en": "Milo", "nl": "Milo"],
        "milo_subtitle": ["en": "Your helpfull shopping doggo", "nl": "Je behulpzame winkelhondje"],
        "ask_milo": ["en": "Ask Milo anything...", "nl": "Vraag Milo alles..."],
        "prompt_cook_title": ["en": "Cook with what I bought", "nl": "Kook met wat ik kocht"],
        "prompt_cook_subtitle": ["en": "Recipes from my last haul", "nl": "Recepten van mijn laatste aankopen"],
        "prompt_cook_message": ["en": "What meals can I cook using the items from my most recent grocery receipt?", "nl": "Welke gerechten kan ik maken met de items van mijn recentste kassaticket?"],
        "prompt_predict_title": ["en": "Predict my next list", "nl": "Voorspel mijn volgende lijstje"],
        "prompt_predict_subtitle": ["en": "What I'll need to restock soon", "nl": "Wat ik binnenkort moet bijkopen"],
        "prompt_predict_message": ["en": "Based on my purchase history, what grocery items will I likely need to restock soon?", "nl": "Op basis van mijn aankoopgeschiedenis, welke boodschappen moet ik binnenkort bijkopen?"],
        "prompt_price_title": ["en": "Spot the price creep", "nl": "Ontdek prijsstijgingen"],
        "prompt_price_subtitle": ["en": "Are my groceries getting pricier?", "nl": "Worden mijn boodschappen duurder?"],
        "prompt_price_message": ["en": "Are any of my regularly purchased grocery items getting more expensive over time?", "nl": "Worden sommige van mijn vaste boodschappen geleidelijk duurder?"],
        "prompt_health_title": ["en": "Rate my basket", "nl": "Beoordeel mijn winkelmandje"],
        "prompt_health_subtitle": ["en": "Nutrition score breakdown", "nl": "Analyse van je voedingsscore"],
        "prompt_health_message": ["en": "Analyze the nutritional balance of my recent grocery purchases and give me a health score", "nl": "Analyseer het voedingsevenwicht van mijn recente boodschappen en geef me een gezondheidsscore"],
        "message_limit_reached": ["en": "Message Limit Reached", "nl": "Berichtlimiet bereikt"],
        "error_encountered": ["en": "I'm sorry, I encountered an error", "nl": "Sorry, er is een fout opgetreden"],
        "please_try_again": ["en": "Please try again.", "nl": "Probeer het opnieuw."],

        // MARK: - Budget
        "set_budget": ["en": "Set Budget", "nl": "Budget instellen"],
        "edit_budget": ["en": "Edit Budget", "nl": "Budget bewerken"],
        "update_budget": ["en": "Update Budget", "nl": "Budget bijwerken"],
        "create_budget": ["en": "Create Budget", "nl": "Budget aanmaken"],
        "budget_question": ["en": "How do you want to track your groceries?", "nl": "Hoe wil je je boodschappen bijhouden?"],
        "total_monthly_budget": ["en": "Total monthly budget", "nl": "Totaal maandbudget"],
        "set_one_amount": ["en": "Set one amount for all groceries", "nl": "Stel één bedrag in voor alle boodschappen"],
        "budget_by_category": ["en": "Budget by category", "nl": "Budget per categorie"],
        "set_limits_category": ["en": "Set limits per category", "nl": "Stel limieten in per categorie"],
        "monthly_budget": ["en": "MONTHLY BUDGET", "nl": "MAANDBUDGET"],
        "per_month": ["en": "per month", "nl": "per maand"],
        "category_targets": ["en": "CATEGORY TARGETS", "nl": "CATEGORIEDOELEN"],
        "category_budgets": ["en": "CATEGORY BUDGETS", "nl": "CATEGORIEBUDGETTEN"],
        "optional": ["en": "Optional", "nl": "Optioneel"],
        "set_limits_categories_eye": ["en": "Set limits on categories you want to keep an eye on", "nl": "Stel limieten in op categorieën die je in de gaten wilt houden"],
        "add_category": ["en": "Add category", "nl": "Categorie toevoegen"],
        "add_category_nav": ["en": "Add Category", "nl": "Categorie toevoegen"],
        "search_categories": ["en": "Search categories", "nl": "Zoek categorieën"],
        "no_categories_found": ["en": "No categories found", "nl": "Geen categorieën gevonden"],
        "auto_renew": ["en": "Auto-renew", "nl": "Automatisch verlengen"],
        "auto_renew_monthly": ["en": "Auto-renew monthly", "nl": "Maandelijks automatisch verlengen"],
        "resets_budget_month": ["en": "Resets budget each month", "nl": "Herstelt budget elke maand"],
        "reuse_budget_monthly": ["en": "Reuse this budget every month", "nl": "Hergebruik dit budget elke maand"],
        "add_categories_track": ["en": "Add categories you want to track", "nl": "Voeg categorieën toe die je wilt bijhouden"],
        "total_saved": ["en": "TOTAL SAVED", "nl": "TOTAAL BESPAARD"],
        "budget": ["en": "Budget", "nl": "Budget"],
        "no_budget_month": ["en": "No budget was set for this month", "nl": "Er is geen budget ingesteld voor deze maand"],
        "track_spending": ["en": "Track your spending and stay on track", "nl": "Volg je uitgaven en blijf op koers"],
        "couldnt_load_budget": ["en": "Couldn't load budget", "nl": "Budget laden mislukt"],
        "remove_budget_confirm": ["en": "This will remove your budget tracking. You can set a new budget anytime.", "nl": "Dit verwijdert je budgetopvolging. Je kunt altijd een nieuw budget instellen."],
        "remove_category_confirm": ["en": "This category will no longer be tracked against a target.", "nl": "Deze categorie wordt niet meer bijgehouden tegenover een doel."],
        "remove_target": ["en": "Remove Target", "nl": "Doel verwijderen"],
        "left_to_spend": ["en": "left to spend", "nl": "nog te besteden"],
        "days_left": ["en": "days left", "nl": "dagen over"],
        "no_results": ["en": "No results", "nl": "Geen resultaten"],
        "no_budget_data": ["en": "No budget data", "nl": "Geen budgetgegevens"],

        // MARK: - Budget Created
        "budget_created": ["en": "Budget Created!", "nl": "Budget aangemaakt!"],
        "monthly_savings_target": ["en": "Monthly Savings Target", "nl": "Maandelijks besparingsdoel"],
        "start_tracking": ["en": "Start Tracking", "nl": "Begin met bijhouden"],

        // MARK: - Budget History
        "budget_history": ["en": "Budget History", "nl": "Budgetgeschiedenis"],
        "loading_history": ["en": "Loading history...", "nl": "Geschiedenis laden..."],
        "failed_load_history": ["en": "Failed to load history", "nl": "Geschiedenis laden mislukt"],
        "no_budget_history": ["en": "No Budget History", "nl": "Geen budgetgeschiedenis"],
        "budget_history_appear": ["en": "Your budget history will appear here once you've set budgets for multiple months.", "nl": "Je budgetgeschiedenis verschijnt hier zodra je meerdere maanden een budget hebt ingesteld."],
        "category_allocations": ["en": "Category Allocations", "nl": "Categorieverdeling"],

        // MARK: - Edit Category Budgets
        "no_category_targets": ["en": "No category targets yet", "nl": "Nog geen categoriedoelen"],
        "add_category_target": ["en": "Add category target", "nl": "Categoriedoel toevoegen"],
        "independent_limits": ["en": "Independent limits — they don't need to add up to your monthly budget.", "nl": "Onafhankelijke limieten — ze hoeven niet op te tellen tot je maandbudget."],
        "edited": ["en": "Edited", "nl": "Bewerkt"],
        "deleted": ["en": "Deleted", "nl": "Verwijderd"],

        // MARK: - Category Budget Detail
        "over_budget": ["en": "Over Budget", "nl": "Over budget"],
        "warning": ["en": "Warning", "nl": "Waarschuwing"],
        "on_track": ["en": "On Track", "nl": "Op koers"],
        "needs_attention": ["en": "Needs Attention", "nl": "Aandacht nodig"],
        "on_track_first": ["en": "On Track First", "nl": "Op koers eerst"],
        "by_group": ["en": "By Group", "nl": "Per groep"],
        "a_z": ["en": "A-Z", "nl": "A-Z"],
        "over": ["en": "Over", "nl": "Over"],
        "almost_at_limit": ["en": "Almost at limit", "nl": "Bijna aan limiet"],
        "used": ["en": "used", "nl": "gebruikt"],
        "categories_found": ["en": "categories found", "nl": "categorieën gevonden"],
        "see_all": ["en": "See All", "nl": "Bekijk alles"],

        // MARK: - Receipts
        "receipt_details": ["en": "Receipt Details", "nl": "Kassaticketdetails"],
        "duplicate_receipt": ["en": "Duplicate Receipt", "nl": "Dubbel kassaticket"],
        "duplicate_receipt_msg": ["en": "This receipt was already uploaded before. The items have not been added again.", "nl": "Dit kassaticket was al eerder geüpload. De items zijn niet opnieuw toegevoegd."],
        "total": ["en": "Total", "nl": "Totaal"],
        "health_score": ["en": "Health Score", "nl": "Gezondheidsscore"],
        "split_with_friends": ["en": "Split with Friends", "nl": "Delen met vrienden"],
        "divide_receipt": ["en": "Divide this receipt among friends", "nl": "Verdeel dit kassaticket onder vrienden"],
        "items": ["en": "Items", "nl": "Items"],
        "no_items_found_receipt": ["en": "No items found", "nl": "Geen items gevonden"],
        "no_items_detected": ["en": "The receipt was uploaded successfully, but no items were detected.", "nl": "Het kassaticket is succesvol geüpload, maar er zijn geen items gedetecteerd."],
        "delete_receipt": ["en": "Delete Receipt", "nl": "Kassaticket verwijderen"],
        "delete_receipt_confirm": ["en": "Are you sure you want to delete this receipt? This action cannot be undone.", "nl": "Ben je zeker dat je dit kassaticket wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt."],
        "no_receipts": ["en": "No Receipts", "nl": "Geen kassatickets"],
        "no_receipts_found": ["en": "No receipts found for this period", "nl": "Geen kassatickets gevonden voor deze periode"],
        "qty": ["en": "Qty", "nl": "Aantal"],

        // MARK: - Receipt Scan
        "got_digital_receipt": ["en": "Got a digital receipt?", "nl": "Heb je een digitaal kassaticket?"],
        "use_share_button": ["en": "Use the Share button from any app", "nl": "Gebruik de Deel-knop vanuit elke app"],
        "wallet_pass_creator": ["en": "Wallet Pass Creator", "nl": "Wallet Pass Aanmaken"],
        "wallet_pass_desc": ["en": "Create Apple Wallet loyalty cards to receive digital receipts", "nl": "Maak Apple Wallet klantenkaarten aan om digitale kassatickets te ontvangen"],
        "top_stores": ["en": "Top Stores", "nl": "Topwinkels"],
        "top_categories": ["en": "Top Categories", "nl": "Topcategorieën"],
        "upload_limit_reached": ["en": "Upload Limit Reached", "nl": "Uploadlimiet bereikt"],
        "upload_limit_month": ["en": "You've used all your receipt uploads for this month. Your limit will reset soon.", "nl": "Je hebt al je kassaticket-uploads voor deze maand opgebruikt. Je limiet wordt binnenkort hersteld."],

        // MARK: - Receipt Upload / Camera
        "upload_receipt": ["en": "Upload Receipt", "nl": "Kassaticket uploaden"],
        "uploading_receipt": ["en": "Uploading Receipt...", "nl": "Kassaticket uploaden..."],
        "processing": ["en": "Processing...", "nl": "Verwerken..."],
        "done_excl": ["en": "Done!", "nl": "Klaar!"],
        "upload_failed": ["en": "Upload Failed", "nl": "Upload mislukt"],
        "try_again": ["en": "Try Again", "nl": "Opnieuw proberen"],
        "dismiss": ["en": "Dismiss", "nl": "Sluiten"],
        "processing_failed": ["en": "Processing Failed!", "nl": "Verwerking mislukt!"],
        "receipt_uploaded": ["en": "Receipt Uploaded!", "nl": "Kassaticket geüpload!"],
        "quality_check_failed": ["en": "Quality Check Failed", "nl": "Kwaliteitscontrole mislukt"],
        "quality_score": ["en": "Quality Score:", "nl": "Kwaliteitsscore:"],
        "minimum_required": ["en": "Minimum Required:", "nl": "Minimum vereist:"],
        "tips": ["en": "Tips:", "nl": "Tips:"],
        "ensure_good_lighting": ["en": "Ensure good lighting", "nl": "Zorg voor goede belichting"],
        "hold_device_steady": ["en": "Hold device steady", "nl": "Houd je toestel stil"],
        "capture_entire_receipt": ["en": "Capture entire receipt", "nl": "Leg het hele kassaticket vast"],
        "review": ["en": "Review", "nl": "Bekijken"],
        "preparing_preview": ["en": "Preparing preview...", "nl": "Voorbeeld voorbereiden..."],
        "retake": ["en": "Retake", "nl": "Opnieuw nemen"],
        "add_more": ["en": "Add More", "nl": "Meer toevoegen"],

        // MARK: - Share Extension
        "preparing_upload": ["en": "Preparing to upload...", "nl": "Voorbereiden om te uploaden..."],
        "uploading_receipts": ["en": "Uploading Receipts", "nl": "Kassatickets uploaden"],
        "uploaded": ["en": "uploaded", "nl": "geüpload"],
        "receipt_failed": ["en": "Receipt Processing Failed!", "nl": "Verwerking van kassaticket mislukt!"],

        // MARK: - Expense Splitting
        "split_receipt": ["en": "Split Receipt", "nl": "Kassaticket delen"],
        "friends": ["en": "Friends", "nl": "Vrienden"],
        "add_friends_split": ["en": "Add friends to split with", "nl": "Voeg vrienden toe om mee te delen"],
        "view_summary_share": ["en": "View Summary & Share", "nl": "Overzicht bekijken & delen"],
        "split_label": ["en": "Split:", "nl": "Verdeling:"],
        "split_summary": ["en": "Split Summary", "nl": "Verdeelresultaat"],
        "split_between": ["en": "Split between", "nl": "Verdeeld onder"],
        "person": ["en": "person", "nl": "persoon"],
        "people": ["en": "people", "nl": "personen"],
        "share_split": ["en": "Share Split", "nl": "Verdeling delen"],
        "split_transaction": ["en": "Split Transaction", "nl": "Transactie delen"],
        "split_with": ["en": "Split with", "nl": "Verdeel met"],
        "each_person_pays": ["en": "Each person pays", "nl": "Elke persoon betaalt"],
        "custom_split": ["en": "Custom split", "nl": "Aangepaste verdeling"],
        "split_correct": ["en": "Split adds up correctly", "nl": "Verdeling klopt"],
        "fix": ["en": "Fix", "nl": "Corrigeren"],
        "add_friends_split_tap": ["en": "Add friends to split", "nl": "Voeg vrienden toe om te delen"],
        "tap_plus_button": ["en": "Tap the + button above to add people to split this expense with.", "nl": "Tik op de + knop hierboven om mensen toe te voegen om deze uitgave mee te delen."],
        "done_editing": ["en": "Done Editing", "nl": "Klaar met bewerken"],
        "add_friend": ["en": "Add Friend", "nl": "Vriend toevoegen"],
        "add_friend_split": ["en": "Add a friend to split with", "nl": "Voeg een vriend toe om mee te delen"],
        "recent_friends": ["en": "Recent Friends", "nl": "Recente vrienden"],
        "friends_name": ["en": "Friend's name", "nl": "Naam van vriend"],

        // MARK: - Promotions
        "save_up_to": ["en": "Save up to", "nl": "Bespaar tot"],
        "total_savings_week": ["en": "TOTAL SAVINGS THIS WEEK", "nl": "TOTALE BESPARING DEZE WEEK"],
        "valid": ["en": "Valid", "nl": "Geldig"],
        "view_in_folder": ["en": "View in folder", "nl": "Bekijk in folder"],
        "smart_switch": ["en": "SMART SWITCH", "nl": "SLIMME WISSEL"],
        "best_value_store": ["en": "Best value", "nl": "Beste keuze"],
        "no_deals_week": ["en": "No deals this week", "nl": "Geen aanbiedingen deze week"],
        "keep_scanning": ["en": "Keep scanning receipts so we can find personalized deals for you", "nl": "Blijf kassatickets scannen zodat we gepersonaliseerde aanbiedingen voor je kunnen vinden"],
        "couldnt_load_deals": ["en": "Couldn't load deals", "nl": "Aanbiedingen laden mislukt"],
        "sniffing_deals": ["en": "Sniffing out your deals...", "nl": "Je aanbiedingen opsnuiven..."],
        "checking_promos": ["en": "Checking promotions across stores", "nl": "Promoties controleren in alle winkels"],
        "finding_promotions": ["en": "Finding promotions", "nl": "Promoties zoeken"],

        // MARK: - Insights
        "daily_insight": ["en": "Daily Insight", "nl": "Dagelijks inzicht"],
        "generating_insight": ["en": "Generating insight...", "nl": "Inzicht genereren..."],
        "insight_by_milo": ["en": "Insight by Milo", "nl": "Inzicht door Milo"],

        // MARK: - Subscription Banner
        "unlock_premium": ["en": "Unlock Premium", "nl": "Ontgrendel Premium"],
        "start_free_trial_banner": ["en": "Start your 14-day free trial", "nl": "Start je 14 dagen gratis proefperiode"],
        "try_free": ["en": "Try Free", "nl": "Probeer gratis"],
        "premium_active": ["en": "Premium Active", "nl": "Premium actief"],
        "upgrade_premium": ["en": "Upgrade to Premium", "nl": "Upgrade naar Premium"],
        "unlock_all_features": ["en": "Unlock all features with a free trial", "nl": "Ontgrendel alle functies met een gratis proefperiode"],
        "premium_feature": ["en": "Premium Feature", "nl": "Premiumfunctie"],
        "unlock": ["en": "Unlock", "nl": "Ontgrendelen"],
        "upgrade_unlimited": ["en": "Upgrade for unlimited uploads", "nl": "Upgrade voor onbeperkt uploaden"],

        // MARK: - Health Score
        "no_data": ["en": "No Data", "nl": "Geen gegevens"],
        "upload_receipts_health": ["en": "Upload receipts to see your health score", "nl": "Upload kassatickets om je gezondheidsscore te zien"],
        "na": ["en": "N/A", "nl": "N/B"],
        "vs_last_period": ["en": "vs last period", "nl": "vs vorige periode"],
        "this_month": ["en": "This Month", "nl": "Deze maand"],
        "last_month": ["en": "Last Month", "nl": "Vorige maand"],

        // MARK: - Transactions
        "transactions": ["en": "Transactions", "nl": "Transacties"],
        "total_amount": ["en": "Total Amount", "nl": "Totaalbedrag"],
        "total_transactions": ["en": "Total Transactions", "nl": "Totaal transacties"],
        "date": ["en": "Date", "nl": "Datum"],
        "item": ["en": "Item", "nl": "Item"],
        "amount": ["en": "Amount", "nl": "Bedrag"],
        "no_transactions": ["en": "No transactions", "nl": "Geen transacties"],
        "total_spent": ["en": "Total Spent", "nl": "Totaal uitgegeven"],
        "by_category": ["en": "By Category", "nl": "Per categorie"],
        "spending_breakdown": ["en": "Spending Breakdown", "nl": "Uitgavenverdeling"],
        "loading_breakdown": ["en": "Loading breakdown...", "nl": "Verdeling laden..."],

        // MARK: - Search
        "search_items": ["en": "Search Items", "nl": "Zoek items"],
        "no_results_search": ["en": "No Results", "nl": "Geen resultaten"],
        "try_adjusting_search": ["en": "Try adjusting your search", "nl": "Probeer je zoekopdracht aan te passen"],
        "groceries": ["en": "Groceries", "nl": "Boodschappen"],

        // MARK: - Year in Review
        "no_spending_data_for": ["en": "No spending data for", "nl": "Geen uitgavegegevens voor"],
        "monthly_breakdown": ["en": "Monthly Breakdown", "nl": "Maandelijks overzicht"],

        // MARK: - Wallet Pass
        "select_barcode": ["en": "Select the barcode you want to use", "nl": "Selecteer de barcode die je wilt gebruiken"],
        "scan_barcode_below": ["en": "Scan barcode below", "nl": "Scan barcode hieronder"],
        "barcode_captured": ["en": "Barcode captured", "nl": "Barcode vastgelegd"],
        "rescan": ["en": "Rescan", "nl": "Opnieuw scannen"],
        "enter_manually": ["en": "Enter manually", "nl": "Handmatig invoeren"],
        "detecting_barcode": ["en": "Detecting barcode...", "nl": "Barcode detecteren..."],
        "creating_pass": ["en": "Creating Pass...", "nl": "Pas aanmaken..."],
        "pass_preview": ["en": "Pass Preview", "nl": "Pas voorbeeld"],
        "pass_preview_desc": ["en": "This is how your loyalty card will appear in Apple Wallet", "nl": "Zo zal je klantenkaart eruitzien in Apple Wallet"],
        "pass_created": ["en": "Pass Created!", "nl": "Pas aangemaakt!"],
        "coming_soon": ["en": "Coming Soon", "nl": "Binnenkort beschikbaar"],
        "position_barcode": ["en": "Position barcode within frame", "nl": "Positioneer barcode in het kader"],
        "barcode_detected": ["en": "Barcode Detected!", "nl": "Barcode gedetecteerd!"],

        // MARK: - Saved Receipts
        "saved_receipts": ["en": "Saved Receipts", "nl": "Opgeslagen kassatickets"],
        "all_cloud_based": ["en": "All Receipts Are Cloud-Based", "nl": "Alle kassatickets zijn in de cloud"],
        "cloud_based_desc": ["en": "Receipts are now automatically uploaded to the cloud when you scan them. Local storage has been disabled.", "nl": "Kassatickets worden nu automatisch naar de cloud geüpload wanneer je ze scant. Lokale opslag is uitgeschakeld."],
        "automatic_backup": ["en": "Automatic cloud backup", "nl": "Automatische cloudback-up"],
        "access_any_device": ["en": "Access from any device", "nl": "Toegang vanaf elk apparaat"],
        "automatic_processing": ["en": "Automatic processing", "nl": "Automatische verwerking"],

        // MARK: - Rate Limit Messages
        "messages": ["en": "messages", "nl": "berichten"],
        "message_limit_period": ["en": "Message limit reached for this period.", "nl": "Berichtlimiet bereikt voor deze periode."],
        "no_receipts_remaining": ["en": "No receipts remaining", "nl": "Geen kassatickets meer over"],
        "one_receipt_remaining": ["en": "1 receipt remaining", "nl": "1 kassaticket over"],
        "receipts_remaining": ["en": "receipts remaining", "nl": "kassatickets over"],
        "upload_limit_period": ["en": "Upload limit reached for this period.", "nl": "Uploadlimiet bereikt voor deze periode."],
        "resets_today": ["en": "Resets today", "nl": "Herstelt vandaag"],
        "resets_in_1_day": ["en": "Resets in 1 day", "nl": "Herstelt in 1 dag"],

        // MARK: - Expandable Receipt Card
        "store_receipt": ["en": "store", "nl": "winkel"],
        "stores_count": ["en": "stores", "nl": "winkels"],

        // MARK: - Budget Ring
        "under_budget": ["en": "Under budget", "nl": "Onder budget"],
        "over_budget_projection": ["en": "Over budget projection", "nl": "Over budget projectie"],
        "already_over_budget": ["en": "Already over budget", "nl": "Al over budget"],

        // MARK: - Subscription Banner (extra)
        "pro": ["en": "Pro", "nl": "Pro"],
        "manage": ["en": "Manage", "nl": "Beheren"],

        // MARK: - Insight Button (extra)
        "daily_spending_insight": ["en": "Daily Spending Insight", "nl": "Dagelijks uitgave-inzicht"],
        "daily_health_insight": ["en": "Daily Health Insight", "nl": "Dagelijks gezondheidsinzicht"],

        // MARK: - Donut Chart / Category Detail
        "avg_price": ["en": "AVG PRICE", "nl": "GEM. PRIJS"],
        "per_item": ["en": "per item", "nl": "per stuk"],
        "items_purchased": ["en": "items purchased", "nl": "items gekocht"],
        "others": ["en": "Others", "nl": "Andere"],
        "of_total": ["en": "of total", "nl": "van totaal"],
        "edit_items": ["en": "Edit Items", "nl": "Items bewerken"],

        // MARK: - Year In Review (extra)
        "total_receipts": ["en": "Total Receipts", "nl": "Totaal kassatickets"],
        "total_spent_year": ["en": "Total Spent", "nl": "Totaal uitgegeven"],
        "avg_per_receipt": ["en": "Avg Per Receipt", "nl": "Gem. per kassaticket"],
        "avg_per_month": ["en": "Avg Per Month", "nl": "Gem. per maand"],
        "top_store": ["en": "Top Store", "nl": "Favoriete winkel"],
        "top_category": ["en": "Top Category", "nl": "Topcategorie"],
        "biggest_receipt": ["en": "Biggest Receipt", "nl": "Grootste kassaticket"],
        "smallest_receipt": ["en": "Smallest Receipt", "nl": "Kleinste kassaticket"],

        // MARK: - Store Detail
        "store_detail": ["en": "Store Details", "nl": "Winkeldetails"],
        "store_breakdown": ["en": "Store Breakdown", "nl": "Winkeloverzicht"],
        "total_visits": ["en": "Total Visits", "nl": "Totaal bezoeken"],
        "avg_per_visit": ["en": "Avg Per Visit", "nl": "Gem. per bezoek"],
        "recent_receipts": ["en": "Recent Receipts", "nl": "Recente kassatickets"],
        "view_all_receipts": ["en": "View All Receipts", "nl": "Bekijk alle kassatickets"],
        "all_time": ["en": "All Time", "nl": "Alle tijd"],
        "receipt_singular": ["en": "receipt", "nl": "kassaticket"],
        "receipt_plural": ["en": "receipts", "nl": "kassatickets"],
        "show_less": ["en": "Show Less", "nl": "Minder tonen"],
        "show_all": ["en": "Show All", "nl": "Alles tonen"],
        "no_receipts_for_store": ["en": "No receipts for this store", "nl": "Geen kassatickets voor deze winkel"],
        "store_singular": ["en": "store", "nl": "winkel"],
        "store_plural": ["en": "stores", "nl": "winkels"],

        // MARK: - Wallet Pass (extra)
        "loyalty_card": ["en": "Loyalty Card", "nl": "Klantenkaart"],
        "add_to_wallet": ["en": "Add to Wallet", "nl": "Voeg toe aan Wallet"],
        "scan_loyalty_card": ["en": "Scan loyalty card", "nl": "Scan klantenkaart"],
        "enter_barcode": ["en": "Enter Barcode", "nl": "Voer barcode in"],
        "barcode_number": ["en": "Barcode Number", "nl": "Barcodenummer"],
        "create_pass": ["en": "Create Pass", "nl": "Pas aanmaken"],
        "select_store": ["en": "Select Store", "nl": "Selecteer winkel"],
        "preview": ["en": "Preview", "nl": "Voorbeeld"],
        "multiple_barcodes_found": ["en": "Multiple Barcodes Found", "nl": "Meerdere barcodes gevonden"],
        "select_barcode_to_use": ["en": "Select the barcode you want to use", "nl": "Selecteer de barcode die je wilt gebruiken"],
        "an_error_occurred": ["en": "An error occurred", "nl": "Er is een fout opgetreden"],
        "store_name": ["en": "Store Name", "nl": "Winkelnaam"],
        "store_details": ["en": "Store Details", "nl": "Winkeldetails"],
        "loyalty_card_barcode": ["en": "Loyalty Card Barcode", "nl": "Klantenkaart barcode"],
        "scan": ["en": "Scan", "nl": "Scan"],
        "take_photo": ["en": "Take a photo", "nl": "Neem een foto"],
        "upload": ["en": "Upload", "nl": "Upload"],
        "from_photos": ["en": "From Photos", "nl": "Uit foto's"],
        "enter_barcode_value": ["en": "Enter barcode value", "nl": "Voer barcodewaarde in"],
        "pass_color": ["en": "Pass Color", "nl": "Paskleur"],
        "store_logo": ["en": "Store Logo", "nl": "Winkellogo"],
        "change_logo": ["en": "Change Logo", "nl": "Logo wijzigen"],
        "add_logo": ["en": "Add Logo", "nl": "Logo toevoegen"],
        "optional_pass_header": ["en": "Optional - appears in the pass header", "nl": "Optioneel - verschijnt in de paskoptekst"],
        "pass_preview_description": ["en": "This is how your loyalty card will appear in Apple Wallet", "nl": "Zo zal je klantenkaart eruitzien in Apple Wallet"],
        "your": ["en": "Your", "nl": "Je"],
        "loyalty_card_ready": ["en": "loyalty card is ready", "nl": "klantenkaart is klaar"],
        "wallet_integration_coming_soon": ["en": "Apple Wallet integration coming soon", "nl": "Apple Wallet-integratie binnenkort beschikbaar"],

        // MARK: - Barcode Camera
        "position_barcode_within_frame": ["en": "Position barcode within frame", "nl": "Positioneer barcode in het kader"],
        "qr_barcodes_loyalty_cards": ["en": "QR codes, barcodes & loyalty cards", "nl": "QR-codes, barcodes & klantenkaarten"],
        "tap_to_capture_or_autodetect": ["en": "Tap to capture or auto-detect", "nl": "Tik om vast te leggen of auto-detectie"],

        // MARK: - Year in Review (singular/plural)
        "transaction_singular": ["en": "transaction", "nl": "transactie"],
        "transaction_plural": ["en": "transactions", "nl": "transacties"],

        // MARK: - Subscription Banner (variant keys)
        "start_14day_trial": ["en": "Start your 14-day free trial", "nl": "Start je 14 dagen gratis proefperiode"],
        "unlock_features_trial": ["en": "Unlock all features with a free trial", "nl": "Ontgrendel alle functies met een gratis proefperiode"],
        "upgrade_unlimited_uploads": ["en": "Upgrade for unlimited uploads", "nl": "Upgrade voor onbeperkt uploaden"],

        // MARK: - Camera
        "normal": ["en": "Normal", "nl": "Normaal"],
        "long_receipt": ["en": "Long Receipt", "nl": "Lang kassaticket"],
    ]
}
